/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Tugas2;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class Posttest2 extends javax.swing.JFrame {

    /**
     * Creates new form Posttest2
     */
    public Posttest2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        labelTTL = new javax.swing.JLabel();
        labelJK = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelRT = new javax.swing.JLabel();
        labelKelDesa = new javax.swing.JLabel();
        labelKec = new javax.swing.JLabel();
        labelKota = new javax.swing.JLabel();
        labelAgama = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelGoldar = new javax.swing.JLabel();
        labelPekerjaan = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfTTL1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        rblakilaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        tfTTL2 = new javax.swing.JTextField();
        tfalamat = new javax.swing.JTextField();
        tfRT1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfRT2 = new javax.swing.JTextField();
        tfKEL = new javax.swing.JTextField();
        tfKEC = new javax.swing.JTextField();
        tfKOTA = new javax.swing.JTextField();
        cbAgama = new javax.swing.JComboBox();
        cbStatus = new javax.swing.JComboBox();
        cbGoldar = new javax.swing.JComboBox();
        tfPEKERJAAN = new javax.swing.JTextField();
        rbwna = new javax.swing.JRadioButton();
        rbwni = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bregister = new javax.swing.JButton();
        breset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORM ISIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        labelNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Nama");

        labelTTL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTTL.setForeground(new java.awt.Color(255, 255, 255));
        labelTTL.setText("Tempat / Tanggal Lahir ");

        labelJK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelJK.setForeground(new java.awt.Color(255, 255, 255));
        labelJK.setText("Jenis Kelamin ");

        labelAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAlamat.setForeground(new java.awt.Color(255, 255, 255));
        labelAlamat.setText("Alamat");

        labelRT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelRT.setForeground(new java.awt.Color(255, 255, 255));
        labelRT.setText("RT/RW");

        labelKelDesa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelKelDesa.setForeground(new java.awt.Color(255, 255, 255));
        labelKelDesa.setText("Kel/Desa");

        labelKec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelKec.setForeground(new java.awt.Color(255, 255, 255));
        labelKec.setText("Kecamatan");

        labelKota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelKota.setForeground(new java.awt.Color(255, 255, 255));
        labelKota.setText("Kota");

        labelAgama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAgama.setForeground(new java.awt.Color(255, 255, 255));
        labelAgama.setText("Agama");

        labelStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(255, 255, 255));
        labelStatus.setText("Status");

        labelGoldar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelGoldar.setForeground(new java.awt.Color(255, 255, 255));
        labelGoldar.setText("Golongan Darah");

        labelPekerjaan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPekerjaan.setForeground(new java.awt.Color(255, 255, 255));
        labelPekerjaan.setText("Pekerjaan");

        label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("Kewarganegaraan");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("/");

        rblakilaki.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup1.add(rblakilaki);
        rblakilaki.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rblakilaki.setForeground(new java.awt.Color(255, 255, 255));
        rblakilaki.setText("Laki laki");
        rblakilaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblakilakiActionPerformed(evt);
            }
        });

        rbperempuan.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup1.add(rbperempuan);
        rbperempuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbperempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbperempuan.setText("Perempuan");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("/");

        cbAgama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Kristen", "Katolik", "Hindu ", "Budha" }));
        cbAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgamaActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kawin", "Belum Kawin", " " }));

        cbGoldar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "AB", "O" }));

        rbwna.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup2.add(rbwna);
        rbwna.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbwna.setForeground(new java.awt.Color(255, 255, 255));
        rbwna.setText("WNA");
        rbwna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbwnaActionPerformed(evt);
            }
        });

        rbwni.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup2.add(rbwni);
        rbwni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbwni.setForeground(new java.awt.Color(255, 255, 255));
        rbwni.setText("WNI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNama)
                    .addComponent(labelTTL)
                    .addComponent(labelJK)
                    .addComponent(labelAlamat)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKelDesa)
                            .addComponent(labelRT)
                            .addComponent(labelKota)
                            .addComponent(labelKec)))
                    .addComponent(labelAgama)
                    .addComponent(labelStatus)
                    .addComponent(labelGoldar)
                    .addComponent(labelPekerjaan)
                    .addComponent(label))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbwna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbwni))
                    .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbGoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(rblakilaki, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbperempuan))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tfTTL1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfTTL2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfNama)
                        .addComponent(tfalamat)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tfRT1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfRT2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfKEL)
                        .addComponent(tfKEC)
                        .addComponent(tfKOTA)
                        .addComponent(tfPEKERJAAN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTTL)
                    .addComponent(tfTTL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfTTL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJK)
                    .addComponent(rblakilaki)
                    .addComponent(rbperempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlamat)
                    .addComponent(tfalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRT)
                    .addComponent(tfRT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfRT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKelDesa)
                    .addComponent(tfKEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKec)
                    .addComponent(tfKEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKota)
                    .addComponent(tfKOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAgama)
                    .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStatus)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGoldar)
                    .addComponent(cbGoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPekerjaan)
                    .addComponent(tfPEKERJAAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(rbwna)
                    .addComponent(rbwni))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("FORM KARTU TANDA PENDUDUK");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(164, 164, 164))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        bregister.setText("Register");
        bregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregisterActionPerformed(evt);
            }
        });

        breset.setText("Reset");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(breset, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bregister)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breset)
                    .addComponent(bregister))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        tfNama.setText("");
        tfTTL1.setText("");
        tfTTL2.setText("");
        tfalamat.setText("");
        tfRT1.setText("");
        tfRT2.setText("");
        tfKEL.setText("");
        tfKEC.setText("");
        tfKOTA.setText("");
        tfPEKERJAAN.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        cbAgama.setSelectedItem(null);
        cbGoldar.setSelectedItem(null);
        cbStatus.setSelectedItem(null);
        
        
    }//GEN-LAST:event_bresetActionPerformed

    private void rblakilakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblakilakiActionPerformed
    
    }//GEN-LAST:event_rblakilakiActionPerformed

    private void rbwnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbwnaActionPerformed
   
    }//GEN-LAST:event_rbwnaActionPerformed

    private void bregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregisterActionPerformed
        
        String nama = tfNama.getText();
        String ttl1 = tfTTL1.getText();
        String ttl2= tfTTL2.getText();
        String alamat = tfalamat.getText();
        String rt1 = tfRT1.getText();
        String rt2 = tfRT2.getText();
        String kelurahan = tfKEL.getText();
        String kecamatan = tfKEC.getText();
        String kota = tfKOTA.getText();
        String pekerjaan = tfPEKERJAAN.getText();
        String agama = cbAgama.getSelectedItem().toString();
        String status = cbStatus.getSelectedItem().toString();
        String goldar = cbGoldar.getSelectedItem().toString();
        
        
        String JenisKelamin = null ;
        if(rblakilaki.isSelected())
            JenisKelamin = rblakilaki.getText();
        else if(rblakilaki.isSelected())
             JenisKelamin = rblakilaki.getText();  
        else if(rbperempuan.isSelected())
            JenisKelamin = rbperempuan.getText();
        else if(rbperempuan.isSelected())
             JenisKelamin = rbperempuan.getText();  
        
        String warganegara = null;
        if(rbwna.isSelected())
            warganegara = rbwna.getText();
        else if(rbwna.isSelected())
            warganegara = rbwna.getText();  
        else if(rbwni.isSelected())
            warganegara = rbwni.getText();
        else if(rbwni.isSelected())
            warganegara = rbwni.getText(); 
    
         Posttest2Outpout output = new Posttest2Outpout(nama,ttl1,ttl2,alamat,rt1,rt2,kelurahan,kecamatan,kota,pekerjaan,agama,status,goldar,JenisKelamin,warganegara);
         output.setVisible(true);
       
        
      
    }//GEN-LAST:event_bregisterActionPerformed

    private void cbAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Posttest2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bregister;
    private javax.swing.JButton breset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbAgama;
    private javax.swing.JComboBox cbGoldar;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelAgama;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelGoldar;
    private javax.swing.JLabel labelJK;
    private javax.swing.JLabel labelKec;
    private javax.swing.JLabel labelKelDesa;
    private javax.swing.JLabel labelKota;
    public static javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPekerjaan;
    private javax.swing.JLabel labelRT;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTTL;
    private javax.swing.JRadioButton rblakilaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JRadioButton rbwna;
    private javax.swing.JRadioButton rbwni;
    private javax.swing.JTextField tfKEC;
    private javax.swing.JTextField tfKEL;
    private javax.swing.JTextField tfKOTA;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfPEKERJAAN;
    private javax.swing.JTextField tfRT1;
    private javax.swing.JTextField tfRT2;
    private javax.swing.JTextField tfTTL1;
    private javax.swing.JTextField tfTTL2;
    private javax.swing.JTextField tfalamat;
    // End of variables declaration//GEN-END:variables
}
